apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: <your_username>
      admin_password: <your_password>

---
kind: Secret
apiVersion: v1
metadata:
  name: credentials
  namespace: default
stringData:
  PROMETHEUS_USERNAME: <your_username>
  PROMETHEUS_PASSWORD: <your_password>
type: Opaque

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboards-k8s-views-global
  labels:
    grafana_dashboard: "1"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboards-k8s-views-global
    key: k8s-views-global.json

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboards-k8s-views-namespaces
  labels:
    grafana_dashboard: "1"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboards-k8s-views-namespaces
    key: k8s-views-namespaces.json

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboards-k8s-views-nodes
  labels:
    grafana_dashboard: "1"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboards-k8s-views-nodes
    key: k8s-views-nodes.json

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboards-k8s-views-pods
  labels:
    grafana_dashboard: "1"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboards-k8s-views-pods
    key: k8s-views-pods.json

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboards-k8s-system-api-server
  labels:
    grafana_dashboard: "1"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboards-k8s-system-api-server
    key: k8s-system-api-server.json

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboards-k8s-system-coredns
  labels:
    grafana_dashboard: "1"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboards-k8s-system-coredns
    key: k8s-system-coredns.json

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboards-k8s-addons-prometheus
  labels:
    grafana_dashboard: "1"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboards-k8s-addons-prometheus
    key: k8s-addons-prometheus.json

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboards-k8s-addons-trivy-operator
  labels:
    grafana_dashboard: "1"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboards-k8s-addons-trivy-operator
    key: k8s-addons-trivy-operator.json